name: "Deploy BauphysikToolWPF"

on:
  push:
    tags:
      - "v*" # triggers workflow when tag looks like this pattern

env:
  SOLUTION_NAME: BauphysikToolWPF.sln
  PROJECT_PATH: ./BauphysikToolWPF.csproj

jobs:

  deploy:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

      # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    - run: dotnet restore ${{ env.PROJECT_PATH }}

    - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true #--no-build

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    - uses: csexton/release-asset-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: BauphysikToolWPF/bin/Release/net8.0-windows10.0.22621.0/publish/win-x64/*.exe
        release-url: ${{ steps.create_release.outputs.upload_url }}