name: "Deploy BauphysikToolWPF"

on:
  push:
    tags:
      - "v*" # triggers workflow when tag looks like this pattern

env:
  SOLUTION_NAME: BauphysikToolWPF.sln
  PROJECT_PATH: ./BauphysikToolWPF.csproj

jobs:

  deploy:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

      # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    # - name: Test
    #   run: dotnet test -c Release --no-build

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --self-contained -p:PublishSingleFile=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: BauphysikToolWPF
          path: BauphysikToolWPF/bin/Release/**/publish/win-x64/

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        files: BauphysikToolWPF/bin/Release/**/publish/win-x64/*.exe
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}